version: 1.0.{build}
os: Visual Studio 2013
install:
before_build:
- cd /d C:\Windows
- echo @echo off "C:\Program Files (x86)\NAnt\bin\NAnt.exe" %* > nant.bat
- set JAVA_HOME=C:\Program Files\Java\jdk1.6.0
- set PATH=C:\Program Files\Java\jdk1.6.0\bin;%PATH%
- cd /d C:\projects\ikvm
build_script:
- nant
test: off